---

- include_vars: main.yml

- stat: path=/home/ubuntu/dagr-1.0/RUNNING_PID
  register: running_pid

- name: Kill old process
  shell: kill $(cat /home/ubuntu/dagr-1.0/RUNNING_PID)
  when: running_pid.stat.exists == True
  tags:
    - kill-process

- name: Delete old dir
  file:
    state: absent
    path: ~/dagr-1.0
  tags:
    - delete-dir

- name: Build executable
  local_action: command /usr/local/bin/activator clean dist
  tags:
    - build-executable

- name: Unarchive project
  unarchive: src="{{ zip_path }}" dest="{{ destination_zip_path }}"
  tags:
    - unarchive-executable

- name: Run start script
  shell: cd ~/dagr-1.0/bin && nohup ./dagr -Dplay.evolutions.db.default.autoApply=true -Dplay.evolutions.db.default.autoApplyDowns=true &
  tags:
    - start-application

