---

- hosts: dagr-prod
  become: no
  gather_facts: False
  remote_user: ubuntu
  roles:
    - { role: project-deployment, tags: ['dagr-prod']}
  environment:
        APPLICATION_SECRET: "{{ vault_application_secret }}"
        DATABASE_URL: "{{ vault_database_url }}"
        DATABASE_USER: "{{ vault_database_username }}"
        DATABASE_PASS: "{{ vault_database_password }}"
